using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using WsjtxUdpLib.Messages;
using WsjtxUdpLib.Messages.Out;

namespace WSJTX_Controller
{
    public partial class WsjtxClient
    {
        public bool ClearCallQueue()
        {
            HaltTuning();
            bool hadCallInProg = callInProg != null;
            CancelQso();                        //Ctrl+W abandons any active contact
            if (hadCallInProg) ResetTxToCq();   //prevent stale mid-QSO TX message on next enable
            if (callQueue.Count == 0) return hadCallInProg;

            callQueue.Clear();
            callDict.Clear();
            ShowQueue();
            if (ctrl.advancedCallLayout) ShowAdvancedQueue(null);
            UpdateMaxTxRepeat();
            deletedAllCalls = true;
            ShowStatus();
            return true;
        }

        //process an automatically-generated request to add a decode to call reply queue
        public void AddSelectedCall(EnqueueDecodeMessage emsg)
        {
            string msg = emsg.Message;
            // Stage A6: classification-derived fields below all read from
            // EffectiveClassification() instead of directly off the wire.
            ClassifiedCall classification = emsg.EffectiveClassification();

            string deCall = WsjtxMessage.DeCall(msg);       //known to not be null
            string toCall = WsjtxMessage.ToCall(msg);       //known to not be null
            string directedTo = WsjtxMessage.DirectedTo(msg);
            bool isCq = emsg.IsCQ();                //CQ format check
            bool isPota = emsg.IsPota();
            bool isDirectedAlert = isCq && IsDirectedAlert(directedTo, classification.IsDx);
            bool isGridReply = WsjtxMessage.IsReply(emsg.Message);
            bool isAcceptableCq = isCq && (directedTo == null /*|| directedTo == "QRP"*/ || (directedTo == "DX" && classification.IsDx) || directedTo == myContinent);
            bool isWantedNewCallOnBand = ctrl.bandComboBox.SelectedIndex == (int)WsjtxClient.NewCallBands.CURRENT && classification.IsNewCallOnBand;
            bool isWantedAzimuth = Ranker.rankMethod < RankMethods.AZ_NQUAD || Ranker.rankMethod > RankMethods.AZ_NWQUAD || emsg.Rank != CallQueueRanker.OffBeamRank;         //within desired azimuth
            bool isWantedMsgType =
                (ctrl.cqOnlyRadioButton.Checked && (isAcceptableCq || WsjtxMessage.Is73orRR73(emsg.Message)))               //CQ, with or without grid info, or (RR)73
                || (ctrl.cqGridRadioButton.Checked && ((isAcceptableCq && WsjtxMessage.Grid(emsg.Message) != null) || isGridReply))             //CQ or reply, with grid info
                || ctrl.anyMsgRadioButton.Checked;                                                 //don't care about grid info
            bool isWantedOrigin = ((ctrl.replyDxCheckBox.Checked && classification.IsDx) || (ctrl.replyLocalCheckBox.Checked && !classification.IsDx)) && (!isCq || isAcceptableCq);
            bool isWantedCall = isWantedMsgType && isWantedOrigin && isWantedAzimuth && (classification.IsNewCallAnyBand || isWantedNewCallOnBand);
            // isWantedDirected: pure classification — whether this decode IS a directed CQ that
            // matches the alert list.  Admission is gated by IsCallingEnabled(WANTED_CQ) in the
            // category switch below; the replyDirCqCheckBox no longer controls admission.
            bool isWantedDirected = isDirectedAlert;

            //refine the call priority
            if (isDirectedAlert && ctrl.replyDirCqCheckBox.Checked && emsg.Priority == (int)CallPriority.DEFAULT)
                emsg.Priority = (int)CallPriority.WANTED_CQ;
            if (!emsg.AutoGen) emsg.Priority = (int)CallPriority.MANUAL_SEL;     //generated by click
            emsg.Category = _awardTagger.DeriveCategory(emsg);   //after Priority set; before SetRank
            SetRank(emsg);           //only after set priority, need this before _callQueueStore.AddCall()

            if (classification.Country == "")
            {
                DebugOutput($"{spacer}Country unknown for '{deCall}', queuing without country");
            }

            int replyDecodePriority = (int)CallPriority.NEW_COUNTRY;      //simulate highest priority
            if (replyDecode != null)
            {
                //DebugOutput($"{spacer}replyDecode.Message: {replyDecode.Message} replyDecode.Priority:{replyDecode.Priority}");
                if (!RecdAnyMsg(replyDecode.DeCall())) replyDecodePriority = replyDecode.Priority;
            }

            UpdateMaxTxRepeat();

            //*******************
            //Auto-generated call
            //*******************
            //auto-generated notification of a call rec'd by WSJT-X;
            if (emsg.AutoGen)       //automatically-generated queue request, not clicked
            {
                if (debugDetail) DebugOutput($"{Time()}");
                if (debugDetail) DebugOutput($"{emsg}{nl}{spacer}msg:'{emsg.Message}' decodeCycle:{CurrentDecodeCycleString()} decodesProcessed:{decodesProcessed} cqPaused:{cqPaused}");

                if (myCall == null || opMode != OpModes.ACTIVE)
                {
                    if (debugDetail) DebugOutput($"{spacer}AddSelectedCall rejected, myCall or opMode");
                    return;
                }

                if (deCall == null)
                {
                    if (debugDetail) DebugOutput($"{spacer}AddSelectedCall rejected, deCall null");
                    return;
                }

                if (deCall == callInProg)
                {
                    if (isCq || emsg.Is73orRR73() || emsg.IsRogers())
                    {
                        toCallStatus = "ready";
                        callInProgLastActivity = isCq ? "calling CQ" : "sent 73";
                    }
                    else
                    {
                        toCallStatus = "busy";
                        callInProgLastActivity = $"working {toCall}";
                    }

                    DebugOutput($"{spacer}AddSelectedCall toCallStatus:{toCallStatus} activity:{callInProgLastActivity}");
                    return;
                }

                // Feature 1: wanted-anywhere alert — fires for any decode of a wanted callsign,
                // regardless of whether the call will be admitted to the transmit queue.
                if (ctrl.wantedCallAnywhereEnabled && wantedCalls.Count > 0
                    && wantedCalls.Contains(deCall)
                    && IsAlertCooledDown(_wantedAnywhereAlertTimes, deCall, WantedAnywhereAlertCooldownSecs))
                {
                    Sounds.PlaySoundEvent(ctrl.soundEnabled_WantedAnywhere, ctrl.soundFile_WantedAnywhere);
                    _wantedAnywhereAlertTimes[deCall] = DateTime.UtcNow;
                    DebugOutput($"{spacer}WantedAnywhere alert: '{deCall}'");
                }

                if (isCq)    //check for unwanted directed CQ
                {
                    if (isDirectedAlert || isAcceptableCq)      //acceptable CQ
                    {
                        if (unwantedCqList.Contains(deCall))
                        {
                            DebugOutput($"{spacer}AddSelectedCall unwanted directed CQ now wanted");
                            unwantedCqList.Remove(deCall);
                        }
                    }
                    else                                        //unwanted CQ
                    {
                        if (!unwantedCqList.Contains(deCall))
                        {
                            DebugOutput($"{spacer}AddSelectedCall rejected, unwanted directed CQ");
                            unwantedCqList.Add(deCall);
                            if (callQueue.Contains(deCall)) _callQueueStore.RemoveCall(deCall);
                        }
                        return;
                    }
                }
                else        //other than a CQ
                {
                    if (unwantedCqList.Contains(deCall))
                    {
                        if (debugDetail) DebugOutput($"{spacer}AddSelectedCall rejected, call following unwanted directed CQ");
                        return;
                    }
                }

                if (callQueue.Contains(deCall))
                {
                    _callQueueStore.UpdateCall(deCall, emsg);
                    if (debugDetail) DebugOutput($"{spacer}AddSelectedCall rejected, already in callQueue");
                    return;
                }

                // Already-worked check: reject calls logged on this band, except POTA (can repeat),
                // new-DXCC categories (the entity being new on band is the relevant criterion), or
                // a station still needed by an actively-checked Rule Definition (e.g. an annual
                // special event award scoped to this year's DateFrom/DateTo). WSJT-X's own
                // "already worked" flag has no concept of an award's date range -- it just checks
                // its own ADIF log for this callsign+band, ever -- so without this exception, a
                // station worked in a past year on this band would be silently hidden from the
                // queue even though this year's award still needs a fresh contact with it.
                // Exact boolean combination lives in AwardMatcher.ShouldRejectAlreadyWorked
                // (Awards/AwardMatcher.cs) so it has direct, exhaustive test coverage.
                bool isNewDxccCategory = emsg.Category == CallCategory.NEW_COUNTRY
                                        || emsg.Category == CallCategory.NEW_COUNTRY_ON_BAND;
                bool isStillNeededByActiveAward = _awardTagger.MatchedAwardRuleId(emsg) != null;
                if (AwardMatcher.ShouldRejectAlreadyWorked(
                        classification.IsNewCallOnBand, isPota, isNewDxccCategory, isStillNeededByActiveAward))
                {
                    DebugOutput($"{spacer}AddSelectedCall: already worked '{deCall}'");
                    return;
                }

                if (IsBlocked(deCall))
                {
                    if (debugDetail) DebugOutput($"{spacer}AddSelectedCall rejected, call blocked");
                    return;
                }

                // ── Call Filters admission gate (Phase 1) ────────────────────────────
                // Classification is already complete (DeriveCategory + SetRank ran above).
                // Each category is admitted iff its Call Filter is enabled in callingEnabled.
                // Manual clicks (!AutoGen) bypass all filters.
                // Note: TO_MYCALL decodes normally take the toMyCall branch (line 2348) and
                // never reach this method.  The case below is defensive insurance only — Jimmy
                // should never hide a station that is calling us.
                bool isAdmitted;
                switch (emsg.Category)
                {
                    case CallCategory.TO_MYCALL:
                        // Always admit — queue admission is never gated by the "Calling Me"
                        // checkbox.  That checkbox controls only Alt+N (next-call) selection.
                        isAdmitted = true;
                        break;
                    case CallCategory.NEW_COUNTRY:
                    case CallCategory.NEW_COUNTRY_ON_BAND:
                    case CallCategory.ALWAYS_WANTED:
                        isAdmitted = IsCallingEnabled(emsg.Category);
                        break;
                    case CallCategory.WANTED_CQ:
                    case CallCategory.POTA:
                    case CallCategory.SOTA:
                        // Directed CQ: filter must be enabled AND the CQ must match the alert list.
                        isAdmitted = IsCallingEnabled(CallCategory.WANTED_CQ) && isWantedDirected;
                        break;
                    case CallCategory.WAS_NEEDED:
                    case CallCategory.DXCC_UNCONFIRMED:
                    case CallCategory.ZONE_NEEDED:
                    case CallCategory.STILL_NEEDED:
                        isAdmitted = IsCallingEnabled(emsg.Category);
                        break;
                    case CallCategory.DEFAULT:
                        // Ordinary CQ: filter must be enabled AND Receive-tab sub-filters must pass.
                        isAdmitted = IsCallingEnabled(CallCategory.DEFAULT) && isWantedCall;
                        break;
                    default:
                        isAdmitted = false;
                        break;
                }
                if (!emsg.AutoGen) isAdmitted = true;

                if (isAdmitted)
                {
                    if (!debugDetail) DebugOutput($"{Time()}");
                    if (!debugDetail) DebugOutput($"{emsg}{nl}{spacer}msg:'{emsg.Message}' decodeCycle:{CurrentDecodeCycleString()} decodesProcessed:{decodesProcessed} cqPaused:{cqPaused}");
                    DebugOutput($"{spacer}AddSelectedCall, isCq:{isCq} deCall:'{deCall}' Priority:{emsg.Priority} Category:{emsg.Category} Rank:{emsg.Rank} IsDx:{classification.IsDx} isWantedCall:{isWantedCall} isWantedDir:{isWantedDirected}");
                    DebugOutput($"{spacer}filterAdmit:{IsCallingEnabled(emsg.Category)} isWantedOrigin:{isWantedOrigin} isWantedMsgType:{isWantedMsgType} isWantedAz:{isWantedAzimuth}");
                    DebugOutput($"{spacer}maxAutoGenEnqueue:{maxAutoGenEnqueue} maxPrevTo:{maxPrevTo} isNewCallAnyBand:{classification.IsNewCallAnyBand} isNewCallOnBand:{classification.IsNewCallOnBand} isWantedNewCallOnBand:{isWantedNewCallOnBand}");
                    DebugOutput($"{spacer}isNewCountry:{classification.IsNewCountry} isNewCountryOnBand:{classification.IsNewCountryOnBand} isPota:{isPota} directedTo:'{directedTo}'");
                    DebugOutput($"{spacer}opMode:{opMode} toCall: '{toCall}' callInProg:'{CallPriorityString(callInProg)}' callQueue.Count:{callQueue.Count} callQueue.Contains:{callQueue.Contains(deCall)} logList.Contains:{logList.Contains(deCall)}");

                    if (!IsCorrectTimePeriodForMode(emsg))
                    {
                        DebugOutput($"{spacer}rejected, wrong time period");
                        return;
                    }

                    if (isPota) DebugOutput($"{_potaLog.DictString()}");
                    List<string> list;
                    if (isPota && _potaLog.TryGetValue(deCall, out list))
                    {
                        string band = FreqToBandStr(dialFrequency / 1e6);
                        if (band == null) band = "???";
                        string date = DateTime.Now.ToShortDateString();     //local date/time
                        string potaInfo = $"{date},{band},{mode}";
                        DebugOutput($"{spacer}potaInfo:{potaInfo}");
                        if (list.Contains(potaInfo))
                        {
                            DebugOutput($"{spacer}rejected, already logged POTA");
                            return;
                        }
                    }

                    bool addedWantedCall = false;
                    bool emsgIsEven = IsEvenCall(emsg);
                    int periodCount = _callQueueStore.PeriodCallCount(emsgIsEven);
                    // Priority calls and admitted HRC-filter calls bypass the per-period queue limit.
                    if (periodCount < maxAutoGenEnqueue || isWantedDirected ||
                        emsg.Category == CallCategory.NEW_COUNTRY ||
                        emsg.Category == CallCategory.NEW_COUNTRY_ON_BAND ||
                        emsg.Category == CallCategory.WAS_NEEDED ||
                        emsg.Category == CallCategory.DXCC_UNCONFIRMED ||
                        emsg.Category == CallCategory.ZONE_NEEDED ||
                        emsg.Category == CallCategory.STILL_NEEDED ||
                        (addedWantedCall = CanAddWantedCall(deCall, emsg, isWantedCall, emsgIsEven)))
                    {
                        int prevTo = 0;
                        int maxTo = MaxTimeoutsForMsg(isPota);
                        DebugOutput($"{spacer}replyDecodePriority:{replyDecodePriority} prevTo:{prevTo} maxPrevPotaTo:{maxPrevPotaTo} maxTo:{maxTo}");
                        if (!timeoutCallDict.TryGetValue(deCall, out prevTo) || prevTo < maxTo)
                        {
                            bool addedCall = _callQueueStore.AddCall(deCall, emsg);
                            if (addedCall && _callQueueStore.PeriodCallCount(emsgIsEven) > ctrl.maxQueuedCallsBase)
                            {
                                if (_callQueueStore.RemoveCallLastForPeriod(emsgIsEven) == deCall) addedCall = false;
                            }

                            DebugOutput($"{spacer}addedCall:{addedCall} decodesProcessed:{decodesProcessed}");
                            if (addedCall && decodesProcessed && !cqPaused)
                            {
                                DebugOutput($"{spacer}late decode(4), restartQueue:{restartQueue}");
                                StartProcessDecodeTimer2();
                            }

                            if (addedCall && toCall != myCall && !_lastAddCallCategoryPlayed)
                                Sounds.PlaySoundEvent(ctrl.callAddedCheckBox.Checked, ctrl.soundFile_CallAdded);
                        }
                        else
                        {
                            DebugOutput($"{spacer}rejected, prevTo:{prevTo}");
                        }
                    }
                    else
                    {
                        DebugOutput($"{spacer}AddSelectedCall: queue full '{deCall}' period:{(emsgIsEven ? "even" : "odd")} periodCount:{periodCount}/{maxAutoGenEnqueue}");
                    }
                    UpdateDebug();
                }
                else
                {
                    // Determine why this call was not admitted for diagnostic logging.
                    string notWantedReason;
                    var filterCat = (emsg.Category == CallCategory.POTA || emsg.Category == CallCategory.SOTA)
                                    ? CallCategory.WANTED_CQ : emsg.Category;
                    if (!IsCallingEnabled(filterCat))
                        notWantedReason = $"filter:{emsg.Category}";
                    else
                        notWantedReason = !isWantedMsgType ? "msgType" : !isWantedOrigin ? "origin" : !isWantedAzimuth ? "azimuth" : "newBand";
                    DebugOutput($"{spacer}AddSelectedCall: not wanted '{deCall}' cat:{emsg.Category} reason:{notWantedReason} msgType:{isWantedMsgType} origin:{isWantedOrigin} az:{isWantedAzimuth} newBand:{classification.IsNewCallAnyBand || isWantedNewCallOnBand}");
                }
                return;
            }
        }

        public void BlockCall(int idx)
        {
            DebugOutput($"{Time()} BlockCall {idx}");
            if (idx < 0) idx = 0;
            if (idx >= callQueue.Count) return;

            EnqueueDecodeMessage dmsg = new EnqueueDecodeMessage();
            string call = _callQueueStore.PeekCall(idx, out dmsg);

            if (call == null) return;

            if (!IsBlocked(call))
            {
                ctrl.ExceptTextBoxAdd(call);       //callqueue updated by BlockedTextChanged()
                DebugOutput($"{spacer}added  {call} to blocked call list");
                StatusView.ShowMessage($"{call} is now blocked", ctrl.callAddedCheckBox.Checked);
            }
            else
            {
                StatusView.ShowMessage($"{call} already blocked", ctrl.callAddedCheckBox.Checked);
            }
        }

        public string GetCallAtIndex(int idx)
        {
            if (idx < 0 || idx >= callQueue.Count) return null;
            return callQueue.ToArray()[idx];
        }

        // Translates a display row index from the normal callListBox (which filters
        // callInProg) to the corresponding true callQueue position.
        // Returns displayIdx unchanged when no mapping exists (e.g., no active QSO).
        public int MapNormalListIndex(int displayIdx)
        {
            if (displayIdx >= 0 && displayIdx < _callListBoxQueueIndices.Count)
                return _callListBoxQueueIndices[displayIdx];
            return displayIdx;
        }

        public bool IsBlockedCall(string call)
        {
            return IsBlocked(call);
        }

        // Called from Controller after lookup or settings change to re-rank and refresh.
        public void SortCallsPublic()  { SortCalls(); ShowQueue(); if (ctrl.advancedCallLayout) ShowAdvancedQueue(null); }
        public void RefreshQueueDisplay() { ShowQueue(); if (ctrl.advancedCallLayout) ShowAdvancedQueue(null); }

        // Called every time Controller.RefreshStillNeedCache() rebuilds activeAwardTags (e.g.
        // right after a QSO is logged) so a call already sitting in the queue tagged "Needed"
        // drops that tag immediately instead of keeping it for the rest of the session.
        // AddSelectedCall only re-derives Category for *new* decodes; a decode of a call
        // already in the queue short-circuits at "if (callQueue.Contains(deCall))" and is
        // handed to CallQueueStore.UpdateCall, which only replaces the stored entry (and its
        // Category) on a progress/priority/grid change -- never just because the award status
        // changed. Without this, working the very station an award tag needed leaves it
        // mislabeled "Needed" in the queue indefinitely.
        public void RefreshQueuedAwardTags()
        {
            bool changed = false;
            foreach (string call in callQueue.ToArray())
            {
                if (!callDict.TryGetValue(call, out EnqueueDecodeMessage d)) continue;
                if (d.Category != CallCategory.STILL_NEEDED) continue;

                CallCategory newCategory = _awardTagger.DeriveCategory(d);
                if (newCategory != d.Category)
                {
                    d.Category = newCategory;
                    changed = true;
                }
            }
            if (changed) RefreshQueueDisplay();
        }

        public bool ManualEnqueueCall(string callsign)
        {
            if (string.IsNullOrEmpty(callsign)) return false;
            if (udpClient2 == null) return false;

            try
            {
                var cmsg = new ConfigureMessage
                {
                    SchemaVersion    = WsjtxMessage.NegotiatedSchemaVersion,
                    Id               = WsjtxMessage.UniqueId,
                    DXCall           = callsign,
                    DXGrid           = "",
                    GenerateMessages = true,
                };
                ba = cmsg.GetBytes();
                udpClient2.Send(ba, ba.Length);
                DebugOutput($"{Time()} >>>>>Sent 'Configure' for manual call to '{callsign}'");
            }
            catch (Exception ex)
            {
                DebugOutput($"{Time()} ManualEnqueueCall failed: {ex.Message}");
                return false;
            }

            EnableTx();

            // Set active-call state so status shows the target callsign, matching normal queue-reply behavior
            SetCallInProg(callsign);
            _manualCallInProg = true;
            cqPaused = false;
            restartQueue = false;
            txTimeout = false;
            tCall = null;
            xmitCycleCount = 0;
            timedOutCall = null;

            // WSJT-X reacts to the Configure command above by updating its own DX Call
            // field, which brings its window to the foreground -- stealing focus away
            // from Jimmy right after the Manual Call dialog closes, so JAWS stops
            // announcing anything in Jimmy. Activate() (not just BringToFront) is used
            // here since real keyboard focus needs reclaiming, not just Z-order --
            // matches the same choice already made for other windows that need actual
            // focus back (e.g. Controller.OpenLogbookWindow, HelpDlg).
            ctrl.Activate();

            return true;
        }

        public void BlockedTextChanged(string text)
        {
            UpdateBlockList(text);

            //remove blocked call(s) from call queue
            foreach (string call in blockList)
            {
                _callQueueStore.RemoveCall(call);
            }
        }

        private void SortCalls()
        {
            var list = new List<EnqueueDecodeMessage>();
            foreach (EnqueueDecodeMessage d in callDict.Values)
            {
                SetRank(d);
                list.Add(d);
            }

            Func<string, bool> isLoTWUser = lookupManager != null ? (Func<string, bool>)lookupManager.IsLoTWUser : null;
            list.Sort((p, q) => Ranker.Compare(p, q, isLoTWUser, lotwBoostEnabled));

            callQueue.Clear();
            foreach (EnqueueDecodeMessage d in list)
            {
                callQueue.Enqueue(d.DeCall());
            }

            ShowQueue();
            if (ctrl.advancedCallLayout) ShowAdvancedQueue(null);
            DebugOutput($"{spacer}callQueue re-sorted{nl}{_callQueueStore.CallQueueString()}");
        }

        //decode rank already set
        private bool CanAddWantedCall(string call, EnqueueDecodeMessage decode, bool isWantedCall, bool isEvenPeriod)
        {
            int periodCount = _callQueueStore.PeriodCallCount(isEvenPeriod);
            // Stage A6: IsNewCallOnBand/IsNewCallAnyBand now read via EffectiveClassification().
            ClassifiedCall decodeClassification = decode.EffectiveClassification();
            if (periodCount < maxAutoGenEnqueue || decodeClassification.IsNewCallOnBand || decodeClassification.IsNewCallAnyBand || IsPrimarySort(RankMethods.MOST_RECENT)) return true;
            if (IsPrimarySort(RankMethods.CALL_ORDER) || !isWantedCall) return false;

            var callArray = callQueue.ToArray();
            EnqueueDecodeMessage d;

            for (int i = 0; i < callQueue.Count; i++)
            {
                if (!callDict.TryGetValue(callArray[i], out d)) continue;
                if (IsEvenCall(d) != isEvenPeriod) continue;
                if (d.Rank < decode.Rank)
                {
                    DebugOutput($"{spacer}CanAddWantedCall, add call:{call}");
                    return true;
                }
            }
            return false;
        }

        private void AddTimeoutCall(string call)
        {
            int callTimeouts;
            if (timeoutCallDict.TryGetValue(call, out callTimeouts))
            {
                timeoutCallDict.Remove(call);
            }
            timeoutCallDict.Add(call, ++callTimeouts);
            DebugOutput($"{Time()} AddTimeoutCall, call:{call} callTimeouts:{callTimeouts}");
        }

        private void ClearCallTimeout(string call)
        {
            if (call == null) return;

            int prevTo;
            if (timeoutCallDict.TryGetValue(call, out prevTo))
            {
                timeoutCallDict.Remove(call);
            }
            timeoutCallDict.Add(call, 0);
        }

        private bool IsBlocked(string call)
        {
            return blockList.Contains(call);
        }

        private void UpdateBlockList(string text)
        {
            blockList = text.Trim().Split(new char[] { ' ' }, StringSplitOptions.RemoveEmptyEntries).ToList<string>();
        }
    }
}
